development:
  adapter: postgresql
  encoding: unicode
  database: garage_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: garage_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: garage_production
  pool: 5